name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-only:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore test project only
        run: dotnet restore StarterApp.Tests

      - name: Run tests
        run: dotnet test StarterApp.Tests --verbosity normal